name: Reveal Secrets
on: workflow_dispatch # מאפשר הרצה ידנית בלבד

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secrets
        run: |
          # אנחנו הופכים את ה-Secret ל-Base64 כדי שגיטהאב לא יזהה אותו וישים כוכביות (***)
          echo "KEYSTORE_FILE_B64: " && echo "${{ secrets.KEYSTORE_FILE }}" | base64
          echo "KEYSTORE_PASSWORD: " && echo "${{ secrets.KEYSTORE_PASSWORD }}" | base64 | sed 's/./& /g'
          echo "KEY_ALIAS: " && echo "${{ secrets.KEY_ALIAS }}" | base64 | sed 's/./& /g'
          echo "KEY_PASSWORD: " && echo "${{ secrets.KEY_PASSWORD }}" | base64 | sed 's/./& /g'
